#?????? ?? ??? ??? ???? ???? ?? ?? ????? ?? ??? 0?? ??.
#(??? instance-id? port:0?? ???? ??? ????? ??? ?????? ?? ??? instance-id? ????.)
#port:0 = ??? ???? ??????~~!!@@!!!@!@!@
server:
  port: 0
spring:
  application:
    name: my-2nd-service
eureka:
  instance:
    #??? ???? ??? ?? -> ?? ?? vm-option? ??? ?? ????~!~!~!@@!~!@
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka



